apiVersion: v1 

kind: Service 

metadata: 

  name: proyecto-kubernetes-service 

spec: 

  selector: 

    app: proyecto-kubernetes

  ports: 

    - protocol: TCP 

      port: 80 

      targetPort: 3000 

  type: LoadBalancer
